### ISSUE TITLE
Listing of installed versions is broken

### ISSUE THREAD

**Issue by kirisu** [tj/n#502] opened 2018-05-09 07:45 UTC
# Issue Template:

### Describe issue including what OS you are using
macOS Sierra 10.12.6. 
#498 seems to have broken being able to list/switch between versions.

### Describe what version of N you have
2.1.10

### Describe how you installed N
N is installed via Homebrew.

### Steps to reproduce issue _1.2.3_
1. `n`

### Describe the results you received
```
sort: stray character in field spec: invalid field specification '2,2V' 

  Error: no installed version

  Usage: n [options/env] [COMMAND] [args]

...
```

### Describe the results you expected
A list of installed versions of node should be displayed, with the ability to switch. 8.11.1 is currently installed.

### What version of npm you are using
6.0.0

**Comment by apertureless** [comment] 2018-05-09 12:44
Got the same error

**Comment by troy0820** [comment] 2018-05-09 15:16
Can you do a `which node` and a `which n` because testing this in a docker container, it works.  I didn't install it through brew which I'm not sure why that would be a problem but the linking of certain things with brew complicate things as well.

**Comment by apertureless** [comment] 2018-05-09 15:25
```bash

❯ which sort
/usr/bin/sort


❯ sort --version
sort (GNU coreutils) 5.93
Copyright (C) 2005 Free Software Foundation, Inc.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

Written by Mike Haertel and Paul Eggert.
```

**Comment by troy0820** [comment] 2018-05-09 15:43
If you do a sort --help do you see the option for -V  ` -V, --version-sort          natural sort of (version) numbers within text`

Your sort version is older so I'm assuming they put the -V option in the newer version of sort.  The reason why we went to this is because when you list the versions with n, it is looking at the folders you have stored where node "lives" hence the `node/10.1.0` so when you select it it uses that directory for your "node".  The `n ls` is showing you what's available within the `https://node.org/dist/` and doesn't have the node/ before the version.

**Comment by stsvilik** [comment] 2018-05-09 21:51
Same here, had to remove `V` option from `2,2V` to at least list the versions

**Comment by kirisu** [comment] 2018-05-10 06:19
Can confirm that pointing to a newer version of sort patches the issue.

**Comment by troy0820** [comment] 2018-05-10 13:16
Can I close this issue? @kirisu @stsvilik @apertureless

**Comment by stsvilik** [comment] 2018-05-11 02:04
@troy0820 How can you close an issue which is still in effect? I can replicate this problem all the time on macOS Sierra (10.12.6) where sort version is `5.93`. On High Sierra where sort is upgraded to `2.3-Apple (99)` your changes work fine. My suggestion is to keep script backwards-compatible and inspect version of `sort` before using unsupported flag.

**Comment by troy0820** [comment] 2018-05-11 02:10
`n@2.1.10` is where the issue is.  The suggested solution of upgrading sort to fix the version listing issue doesn't come with a feature that isn't supported in a different version of this package.  The person who put in the issue confirmed that the issue is resolved with upgrading `sort`.  If you don't want to upgrade sort and want the versions to not be in "order" you can use `n@2.18` or earlier which offer the same functionality.

**Comment by stsvilik** [comment] 2018-05-11 02:26
@troy0820  :/ I would still tailor towards backwards-compatibility and retain "no surprises" policy since this issue will come up over and over again for unprepared users. Yes, I can upgrade `sort` (or rather whole OS), but don't believe this to be the right solution.

**Comment by apertureless** [comment] 2018-05-11 08:47
Okay, stupid question but how to upgrade sort on macosx without upgrading the whole os? 

I have `coreutils` installed with `gsort` however aliasing does not work for `n`.

**Comment by troy0820** [comment] 2018-05-11 18:53
@stsvilik I agree with you 100%.  The problem is that the newer version will be published with the sort issue from the previous version.  If I go forward with a newer version of this that fixes this _(but not fix it sort issue where `sort -k 1,1 -k 2,2V -t /` fixes it )_ I will end up with a change between versions that are not consistent.  The best I can do is back port the changes to the older versions that don't have this problem when listing versions.  I can add something in the documentation that addresses this issue and pin it to the version with no issue.  Because node/10.0.0 is the issue of sorting the displayed versions with the old method of sort, going forward we will still have this problem unless someone makes a PR changing that behavior. 

@apertureless I have not tried this but this seems to be what you are asking for
https://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/

**Comment by stsvilik** [comment] 2018-05-12 20:09
@troy0820 I have a strange feeling that if `n` was written in JavaScript we wouldn't be wasting time defending our decisions :). Anyway - additional documentation and back-porting all sounds better than broken, so I'll let you do what you need do 👍

**Comment by JohnRGee** [comment] 2018-05-13 07:51
The sort could be done the old numeric key way by separating out the prefix for the sort, for example by changing the slash to a dot and back again. Keeping it simple:

```
find $BASE_VERSIONS_DIR -maxdepth 2 -type d \
    | sed 's|'$BASE_VERSIONS_DIR'/||g' \
    | egrep "/[0-9]+\.[0-9]+\.[0-9]+$" \
    | sed 's|/|.|' \
    | sort -t . -k2,2n -k3,3n -k4,4n \
    | sed 's|\.|/|'
```

**Comment by backspaces** [comment] 2018-05-18 18:44
Add me to the list .. n breaks with

> sort: stray character in field spec: invalid field specification `2,2V'
Error: no installed version

I'd upgrade sort if there is an easy way to do it. I *don't* want to install the entire gnu ecology like the article referred to above suggests!

**Comment by troy0820** [comment] 2018-05-18 18:49
Closing issue because of the new version `2.1.1` fixes the sort issue.  Upgrading n will fix this issue.

**Closed by troy0820** 2018-05-18 18:49 UTC

**Comment by backspaces** [comment] 2018-05-18 21:55
Sweet, thanks.
