### ISSUE TITLE
n prune returns 1 as exit code

### ISSUE THREAD

**Issue by Bjorn248** [tj/n#529] opened 2018-10-10 15:20 UTC
# Issue Template:

Using CentOS/RHEL 7

n version 2.1.12

Installed n by placing the script into a directory in PATH

### Steps to reproduce
1. `n prune`
2. `echo $?`

### Describe the results 
exit code was 1

### Describe the results you expected

Exit code should be 0 unless there is an error

### What version of npm you are using

npm version 6.2.0

**Comment by JohnRGee** [comment] 2018-10-12 08:58
Optional question: is this affecting how you use `n` in practice, or just something you noticed?

I reproduced after a couple of tries. Technically, I think the issue is a bogus `shift` command copied from the `rm` function to the `prune` function` causing the exit status to be (incorrectly) non-zero under some circumstances.

Steps to reliably reproduce:
```
n latest
n prune
n lts
n prune
echo $?
```

**Comment by Bjorn248** [comment] 2018-10-12 14:40
@JohnRGee I use `n` with chef and chef expects commands to have sane exit codes. I had chef client runs failing which is how I found this issue

**Comment by troy0820** [comment] 2018-11-05 20:38
Issue closed from landed commit in PR #531

**Closed by troy0820** 2018-11-05 20:38 UTC
