### ISSUE TITLE
n latest works but n io latest fail with cp: cannot stat

### ISSUE THREAD

**Issue by tuananh** [tj/n#298] opened 2015-07-29 13:38 UTC
OS: Kubuntu 15.04

```
cp: cannot stat ‘/usr/local/n/versions/io//bin’: No such file or directory
cp: cannot stat ‘/usr/local/n/versions/io//lib’: No such file or directory
cp: cannot stat ‘/usr/local/n/versions/io//share’: No such file or directory
```

**Comment by maxrimue** [comment] 2015-07-29 13:42
Does `n io ls` get you any output?

**Comment by tuananh** [comment] 2015-07-29 13:43
@maxrimue `n io ls` gives me a blank line

**Comment by maxrimue** [comment] 2015-07-29 13:43
Try to upgrade OpenSSL

**Comment by tuananh** [comment] 2015-07-29 13:45
i have `OpenSSL 1.0.1f 6 Jan 2014`. `sudo apt-get update` and `upgrade` do nothing as everything is updated.

**Comment by maxrimue** [comment] 2015-07-29 13:49
@tuananh I have no idea why Ubuntu offers you no newer version of OpenSSL, but the version you run, 1.0.1, is really old. In this version, the heartbleed bug wasn't yet fixed, which is why some servers don't work with an OpenSSL version below 1.0.1g. I'll try to find out what's going on here

**Comment by maxrimue** [comment] 2015-07-29 14:00
@tuananh Does `apt-get dist-upgrade` upgrade OpenSSL?

**Comment by tuananh** [comment] 2015-07-29 17:51
@maxrimue that one does nothing as well.

**Comment by maxrimue** [comment] 2015-07-31 14:12
`curl -Is https://iojs.org/ | head -n 1` should get you `HTTP/1.1 200 OK`, if not, it's definitely something wrong with your system rather than n or your installation of n

**Comment by husless** [comment] 2015-09-12 10:37
On Ubuntu 14.04:

`sudo n latest` sometime gives:

```bash
$ sudo n latest
cp: cannot stat ‘/usr/local/n/versions/node//bin’: No such file or directory
cp: cannot stat ‘/usr/local/n/versions/node//lib’: No such file or directory
cp: cannot stat ‘/usr/local/n/versions/node//share’: No such file or directory

```

sometime gives:

```bash
$ sudo n latest

     install : node-v0.12.7
       mkdir : /usr/local/n/versions/node/0.12.7
       fetch : https://nodejs.org/dist/v0.12.7/node-v0.12.7-linux-x64.tar.gz

```

sometime gives:

```bash
$ sudo n latest

     install : node-v4.0.0
       mkdir : /usr/local/n/versions/node/4.0.0
       fetch : https://nodejs.org/dist/v4.0.0/node-v4.0.0-linux-x64.tar.gz
```

**Comment by maxrimue** [comment] 2015-09-13 15:39
@husless What do you mean by 'sometimes'? Did you do anything to change the output or behaviour of the program or your system?

**Comment by husless** [comment] 2015-09-15 05:32
@maxrimue Sorry, I did not discribe it clearly. I did not change the anything of the program or the system. I wanted to upgrade node to node-v4.0.0, and executed commands in terminal:

```bash
sudo npm install -g n
sudo n latest
```

I tried  `sudo n latest` at least  5 times sequently. It gave me either the `cp: cannot stat ...` error or installing node-v0.12.7.

I've finally upgraded node to node-v4.0.0 using `sudo n latest`.

**Comment by tedgaydos** [comment] 2015-09-15 12:59
So node and io have merged. We need to look at filter logic for latest and stable to make sure everything is good now that the major version for node is not zero.

**Comment by maxrimue** [comment] 2015-09-17 14:24
@tedgaydos I think there won't be any more test builds that aren't completely stable (like 0.11.x), so I think we could just pull the `stable` option completely and let `latest` just pull the latest (so from `https://nodejs.org/dist/latest/`)

**Comment by maxrimue** [comment] 2015-09-17 14:29
But aside from that, I don't think that the 4.x.x release is causing @husless's issue as `n latest` installed v4.0.0 for me just fine

**Comment by tedgaydos** [comment] 2015-09-17 18:03
From the first error listed, it looks like a problem with curl reading the url. I am not able to reproduce those results on Ubuntu or Linux Mint.

**Comment by maxrimue** [comment] 2015-09-17 19:20
@tedgaydos As it works now, it seems like the issue was related to the system rather. The last time I've seen outputs like `cp: cannot stat ‘/usr/local/n/versions/node//bin’: No such file or directory`, it was due to `curl` which couldn't connect to the servers when it was outdated (due to Heartbleed)

**Comment by Sean-Wang** [comment] 2015-12-18 05:09
@tuananh Upgrade OpenSSL please.

![Uploading image.png…]()
![Uploading image.png…]()

**Comment by Sean-Wang** [comment] 2015-12-18 05:14
@tuananh Upgrade OpenSSL first of all. Thanks @maxrimue.

![1__seanwang_192_____zsh_](https://cloud.githubusercontent.com/assets/1193073/11889908/4a4dc384-a589-11e5-87c2-e6c7d43c28db.png)

![image](https://cloud.githubusercontent.com/assets/1193073/11889873/d85ec5ac-a588-11e5-8bf5-d3c0bded236a.png)

**Comment by hufeng** [comment] 2017-02-03 15:35
i'm came cross the same problem

**Closed** 2017-02-04 00:51 UTC
