### ISSUE TITLE
add option to install LTS version

### ISSUE THREAD

**Issue by warrickhill** [tj/n#319] opened 2015-10-30 13:10 UTC
Now node has moved to having a stable version and an LTS version it would be good if we could install the LTS version like this `n --lst`

**Comment by themphill** [comment] 2015-10-30 14:30
+1

**Comment by tnguyen14** [comment] 2015-11-03 17:14
Looks like this is a duplicate of #313

**Comment by tedgaydos** [comment] 2015-11-04 18:12
It is a duplicate. Will track with #313

**Closed by tedgaydos** 2015-11-04 18:12 UTC
