### ISSUE TITLE
can we have `n lts` (n --lts) for 4.2 branch?

### ISSUE THREAD

**Issue by dym-cx** [tj/n#321] opened 2015-11-04 16:48 UTC
not sure why 5.0.0 is "latest" _and_ "stable" (with 10 breaking changes), but i would like to stay on latest 4.2.x just so `nodemon` and other modules wouldnt suddenly refuse to work or even install properly

thx

**Comment by tedgaydos** [comment] 2015-11-04 18:12
Duplicate of #313

**Closed by tedgaydos** 2015-11-04 18:12 UTC
