### ISSUE TITLE
Installed on Ubuntu 16.04.2 LTS, and `n <version>` doesn't change which node version I am using.

### ISSUE THREAD

**Issue by trusktr** [tj/n#451] opened 2017-07-17 19:53 UTC
# Issue Template:

### Describe issue including what OS you are using

Ubuntu 16.04.2 LTS

### Describe what version of N you have

2.1.7

### Describe how you installed N

`npm i -g n` while on node v4.2.6 which is installed with default apt-get registry for my version of Ubuntu.

### Steps to reproduce issue _1.2.3_

```sh
npm i -g n
n latest
node -v
```

### Describe the results you received

 It outputs `v4.2.6`, but I was expecting `v8.1.4`

### What version of npm you are using

5.0.3

### Additional information you deem important (e.g. issue happens only occasionally):

```
> which n
/usr/local/bin/n
> node -v
v4.2.6
```

**Comment by trusktr** [comment] 2017-07-17 19:54
To work around the problem for now, I've symlinked /usr/local/bin/node to the version installed in /usr/local/n/

**Comment by troy0820** [comment] 2017-07-18 23:56
what is the output of which node? It seems the symlink didn't happen or the node you are using isn't the one from n.  I have a docker container that is Ubuntu:16.04 you can try at `troy0820/node-n:latest`.  I'm trying to reproduce your issue, but I'm not having any luck.

**Comment by stephenmcm** [comment] 2017-07-19 04:14
I'm getting the same result.
```
>which node
/usr/local/bin/node
>ls -la /usr/local/bin/
lrwxrwxrwx  1 root root       27 Jul 19 13:52 n -> ../lib/node_modules/n/bin/n
-rwxr-xr-x  1 root root 29851602 Jul 19 13:52 node
lrwxrwxrwx  1 root root       38 Jul 19 13:52 npm -> ../lib/node_modules/npm/bin/npm-cli.js
```

**Comment by trusktr** [comment] 2017-07-19 05:24
```
~ ❯ which node
/usr/local/bin/node
```

Hmmm, maybe that's not the default one? I think `sudo apt-get install nodejs` installs `/usr/bin/nodejs`, but I'm not sure about `/usr/local/bin/node`.

**Comment by adamreisnz** [comment] 2017-08-27 02:42
I seem to run into the same issue where `n` links the new version to `/usr/local/bin/nodejs` whereas my install has Node running from `/usr/local/bin/node`.

I've installed Node using the following:

```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install nodejs
```

**Comment by adamreisnz** [comment] 2017-08-27 02:54
May actually be a duplicate of https://github.com/tj/n/issues/381
I've found that indeed after restarting the shell it did find the correct Node version.

**Comment by ivarni** [comment] 2017-09-03 06:39
Restarting shell didn't work for me. It turned out that something (I'm guessing heroku toolbelt?) had added a new binary for me.
```
➜  ~ sudo n 6.7.0
➜  ~ node --version
v8.1.4
➜  ~ which -a node
/usr/local/heroku/bin/node
/usr/local/bin/node
/usr/bin/node
➜  ~ sudo ls -ltr /usr/local/heroku/bin 
total 33960
-rwxrwxr-x 1  500  500 34764936 Jul 11 03:10 node
-rw-r--r-- 1 root root      310 Jul 20 00:18 heroku.js
-rwxr-xr-x 1 root root      836 Jul 20 00:18 heroku
➜  ~ sudo rm /usr/local/heroku/bin/node 
➜  ~ node --version
v6.7.0
```
Removing that worked.

**Comment by sleekweasel** [comment] 2017-09-08 12:59
I had something similar:

```
$ which -a node
/usr/local/bin/node
/usr/bin/node
$ /usr/local/bin/node -v
v8.4.0
$ which node
/usr/local/bin/node
$ /usr/bin/node -v
v5.4.1
$ node -v
v5.4.1
$ rehash
$ node -v
v8.4.0
```

So I needed to rehash (or quit and re-run the shell) to fix this.

This was from doing the git clone version of install and then the foregoing n-based installs, all in one shell. Hard to think how to fix this, except perhaps by making 'n' check whether 'which node' changes value and printing a ***** BIG OBVIOUS WARNING ***** about it for stupid people like me. :)

Here's hoping I won't suffer the npm install Buffer.alloc bug now.

**Comment by dandv** [comment] 2018-02-28 11:46
Same problem still, as of March 2018 (well, it's the same `n` version, 2.1.7). Restarting bash did fix it.

**Comment by guido4000** [comment] 2018-03-24 18:07
It might help to remove the pre-installed version of node
`sudo apt remove nodejs`

**Comment by DMalagonH** [comment] 2018-07-12 11:51
I solved it.  
I uninstalled node with apt-get and then set 777 permisions to /usr/local/bin/node
```
sudo apt-get remove nodejs
sudo chmod 777 -R /usr/local/bin/node
```
Previously I had installed node 8.11.3 with:
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```
and then I installed n with:
```
sudo npm -g install n
sudo n latest
```
But, when I changed the node version with n to 10.5.0 for example `node -v` showed 8.11.3. However, if I use `sudo node -v` it showed the correct version (10.5.0)

**Comment by FranzSkuffka** [comment] 2018-09-20 15:36
@guido4000 thx - that fixed it.

**Comment by shadowspawn** [comment] 2019-03-22 22:12
Restarting the shell was the most common fix.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Closed by shadowspawn** 2019-03-22 22:12 UTC

**Comment by shadowspawn** [comment] 2019-11-16 04:01
`n` v6.1.2 has additional output for the situation when node command location changes, and the old location may be remembered by the current shell.

e.g.
```
Note: the node command changed location and the old location may be remembered in your current shell.
         old : /usr/bin/node
         new : /usr/local/bin/node
To reset the command location hash either start a new shell, or execute PATH="$PATH"
```
 (Longer transcript: https://github.com/tj/n/issues/588#issuecomment-554601529)

**Comment by jokermt235** [comment] 2020-01-18 15:37
After installing bu using   root permissions i simply type >exit in terminal and relogin again as sudo 
my node , and npm versions became a stable as I prefered before!

**Comment by alexisprog** [comment] 2020-01-23 10:48
export PATH=$PATH:/usr/local/bin/node

**Comment by wale-bant** [comment] 2020-02-23 09:20
> export PATH=$PATH:/usr/local/bin/node

This solved it for me.

**Comment by alancrisanto** [comment] 2021-11-26 03:14
This helped me.
https://heynode.com/tutorial/install-nodejs-locally-nvm/

**Comment by shadowspawn** [comment] 2021-11-26 03:20
@alancrisanto 
Note: those are instructions for installing and using `nvm`, which is a different node version manager.
