### ISSUE TITLE
Cannot install latest

### ISSUE THREAD

**Issue by ChickenFur** [tj/n#425] opened 2017-04-04 23:55 UTC
# Issue Template:

### Describe issue including what OS you are using

when running n latest it attempts to install  node-v7.8.0 but fails with the message:
Error: invalid version 7.8.0

MacOS X El Capitan
April 4th 4:55pm Pacific time

### Describe what version of N you have
2.1.3

### Describe how you installed N
npm install -g n

### Steps to reproduce issue _1.2.3_
1. n latest

### Describe the results you received
``` install : node-v7.8.0
  Error: invalid version 7.8.0
```

### Describe the results you expected
Download and install

### What version of npm you are using
3.10.10

### Additional information you deem important (e.g. issue happens only occasionally):

* Output of `which n:`2.1.3
* Output of `node -v:` 6.10.0

**Comment by troy0820** [comment] 2017-04-05 00:15
Cloudflare stuff going on may be impacting this.  node/node  has already put an issue in about this. https://github.com/nodejs/nodejs.org/issues/1191

**Comment by troy0820** [comment] 2017-04-05 02:07
I would also recommend you getting the latest version of `n`.  We are at 2.1.7.  Try it now, because they just closed this issue. @ChickenFur

**Comment by amadsen** [comment] 2017-04-05 14:32
I can confirm that the npmjs download issue was causing the failure for me. I wonder if we might want to add an environment variable for specifying a mirror to download from instead (& possibly better error messaging. A 5xx status code should result in "Version unavailable: server error." Or similar, not"Invalid version".)

**Comment by troy0820** [comment] 2017-04-05 14:38
The mirror that we get the node versions come from the source of truth itself, `https://nodejs.org/dist/`.  So when the CloudFlare issue came up yesterday, it crippled nvm as well.  

I agree that the error messaging gives problematic troubleshooting and that will be addressed.  Any other mirrors not associated with nodejs.org will have to be vetted to be added to this project.

I am closing this issue.

**Closed by troy0820** 2017-04-05 14:38 UTC

**Comment by amadsen** [comment] 2017-04-20 06:45
I just noticed that we already have environment variables for setting the NODE_MIRROR and IO_MIRROR:

~~~bash
MIRROR=(${NODE_MIRROR-https://nodejs.org/dist/}
        ${IO_MIRROR-https://iojs.org/dist/})
~~~

That's actually all I was looking for in that regard. Thanks for your work!
