### ISSUE TITLE
about node install problem

### ISSUE THREAD

**Issue by haozxuan** [tj/n#283] opened 2015-06-16 15:49 UTC
hi, I have a problem about install node.eg:
![image](https://cloud.githubusercontent.com/assets/8748015/8187410/2f51de1e-1482-11e5-80d5-86fd804950e9.png) 
I can not install latest node,because eg:
![image](https://cloud.githubusercontent.com/assets/8748015/8187439/5063b7e4-1482-11e5-8062-7fb144d4f720.png)
hope resolve. 
Thanks

**Comment by maxrimue** [comment] 2015-06-16 15:54
What architecture is your processor running with?

**Comment by tedgaydos** [comment] 2015-06-16 17:38
Is nodejs.org blocked from your location? Running `n ls` should print out all available versions. But, your screenshot does not show it.

**Comment by haozxuan** [comment] 2015-06-17 01:59
@maxrimue 
![image](https://cloud.githubusercontent.com/assets/8748015/8198330/694bc576-14d7-11e5-9f11-86d11af117bf.png)
redhat 5 and  x86

**Comment by haozxuan** [comment] 2015-06-17 02:02
@tedgaydos 
![image](https://cloud.githubusercontent.com/assets/8748015/8198351/a694694c-14d7-11e5-8b79-dccfd10179b2.png)
![image](https://cloud.githubusercontent.com/assets/8748015/8198359/e531f930-14d7-11e5-90a1-c5b6517a4295.png)

**Comment by haozxuan** [comment] 2015-06-17 13:16
yeah,  I note #command -v curl > /dev/null && GET="curl -# -L",this line. because this:
![image](https://cloud.githubusercontent.com/assets/8748015/8207736/09705cb6-1536-11e5-8f9b-b5ead4d62548.png)

**Comment by maxrimue** [comment] 2015-06-17 13:21
So it seems to be the same problem like in #284, it's because of the curl in your path, have you changed it somehow?

**Comment by haozxuan** [comment] 2015-06-17 14:03
all curl  add -k

**Comment by maxrimue** [comment] 2015-06-17 15:56
That would disable checking for certificates, you can apply those changes to your copy, it would work. However, it is a problem caused by your `curl`, and not `n`. It should work without the `-k` flag, too.

**Comment by haozxuan** [comment] 2015-06-18 03:23
haha, i found it. because my development service not installend openssl, when yum install openssl it works well

**Comment by maxrimue** [comment] 2015-06-18 12:51
That's good to hear, I'll close this one now then

**Closed by maxrimue** 2015-06-18 12:51 UTC
