### ISSUE TITLE
"npm install xyz" produces "asyncWrite is not a function"

### ISSUE THREAD

**Issue by changjunhao** [tj/n#508] opened 2018-06-01 03:51 UTC
# Issue Template:

### Describe issue including what OS you are using

I'm using CentOS 

### Describe what version of N you have
--version output: 2.1.11

### Describe how you installed N

npm install -g n_

### Steps to reproduce issue _1.2.3_
_i.e._
1. n latest

### What version of npm you are using

 npm --version output: 6.1.0

### Additional information you deem important (e.g. issue happens only occasionally):

* Output of `which n:` 2.1.11
* Output of `node -v:` 10.3.0

#### (paste your output here)
<img width="1093" alt="2018-06-01 11 50 34" src="https://user-images.githubusercontent.com/7688639/40820260-1ec738a0-6592-11e8-9547-171ba33433c5.png">

**Comment by troy0820** [comment] 2018-06-01 04:13
I tried this in a docker container and reproduced the same error.  I looked around within npm because this isn't an N issue.  I found these issues: [pna.nextTick](https://github.com/npm/npm/issues/20848) and [this one](https://github.com/npm/npm/issues/20822).  I'm going to close this issue but the solution I had was to use node 8.11.2 with npm version 5.6.0 to solve this issue.

**Closed by troy0820** 2018-06-01 04:13 UTC

**Comment by ozjd** [comment] 2018-06-05 11:55
Had the same issue, reverting to stable, updating npm, then upgrading node to latest worked for me.

See https://github.com/npm/npm/issues/20848#issuecomment-394680906

**Comment by Norbz** [comment] 2018-06-14 09:48
@ozjd linked solution worked for me
Seems to be a bug with 'n' indeed. Node 10.3 and 10.4 have the same issue

**Comment by mateodelnorte** [comment] 2018-06-22 12:43
I am still getting this issue.

**Comment by rosshadden** [comment] 2018-06-22 12:48
@mateodelnorte Did you try what @ozjd linked above? It worked for me.

**Comment by mateodelnorte** [comment] 2018-06-22 13:00
I was actually able to revert back to lts, upgrade n, switch to 10, and
then publish.

Thanks!

**Comment by deksden** [comment] 2018-06-25 08:36
It was issue with n: https://npm.community/t/asyncwrite-is-not-a-function-at-node-10-3-0-and-npm-6-1-0/193

**Comment by Andrewsopoku** [comment] 2018-07-04 06:30
Use sudo when switching node version with n
example `sudo n 10.4.1
`

**Comment by rosshadden** [comment] 2018-07-13 18:38
@Andrewsopoku That would switch the `n` version for the root user, not for your user... Unless you have `n` configured very strangely it won't actually solve or even bypass the issue.

**Comment by JohnRGee** [comment] 2018-07-18 10:15
This has been fixed in latest version of `n`. (See Issue #510 for and PR #470 for further info.)

**Comment by prcongithub** [comment] 2018-09-04 09:07
This woks for me:
```
rm -rf /usr/local/lib/node_modules
rm -rf /usr/local/bin/node
rm -rf /usr/local/bin/npm
n 10.9.0
node -v
npm -v
```

**Comment by designgawd** [comment] 2018-09-11 21:44
@prcongithub That was the solution I was looking for! Thanks, worked in my VM.

**Comment by shengoo** [comment] 2018-09-22 08:00
> This woks for me:
> 
> ```
> rm -rf /usr/local/lib/node_modules
> rm -rf /usr/local/bin/node
> rm -rf /usr/local/bin/npm
> n 10.9.0
> node -v
> npm -v
> ```

Thanks, it worked!

**Comment by deksden** [comment] 2018-09-23 11:33
Maybe some way of complete uninstall of all node versions (like mentioned above) can be part of n?

**Comment by JohnRGee** [comment] 2018-09-24 10:33
`n` was updated in v2.1.12 to address this issue, which is due to major changes in layout in the npm modules folder. So an important step in addition to fixing npm is to also update n, so the problem does not happen again. For example to fix up broken npm *and* update n (add sudo if required):

```bash
$ rm /usr/local/bin/node
$ rm -rf /usr/local/lib/node_modules/npm
$ n latest
$ npm --version
6.4.1
$ npm install -g n
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
+ n@2.1.12
updated 1 package in 0.466s
```

**Comment by PepperTeasdale** [comment] 2018-10-18 19:36
@JohnRGee I'm not seeing v2.1.12 in the [releases](https://github.com/tj/n/releases). Would it be possible to make a release for this version so the homebrew version of `n` can be bumped? https://github.com/Homebrew/homebrew-core/blob/master/Formula/n.rb

Bumped into this issue the other day and it took me a while to find this as the root cause

**Comment by troy0820** [comment] 2018-10-18 19:45
Yeah, I'll make a new release for 2.1.12

**Comment by PepperTeasdale** [comment] 2018-10-18 19:51
Thanks!

**Comment by shadowspawn** [comment] 2019-03-12 09:14
See https://github.com/tj/n/issues/508#issuecomment-423933394

**Comment by gerenrot** [comment] 2019-08-26 12:37
This worked for me on CentOS without having to reinstall node:
`$(dirname $(n which $(node -v)))/npm i -g npm`

It's based on @iarna one liner here https://github.com/tj/n/issues/510#issue-330786549

**Comment by AchintyaAshok** [comment] 2021-06-12 16:57
https://github.com/tj/n/issues/508#issuecomment-471895322

After you do this, go to https://nodejs.org/en/ and reinstall node. Then, install a node package manager like `n` => `npm install -g n`.
